{% set version = "0.2-3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sparsesvd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sparsesvd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sparsesvd/sparsesvd_{{ version }}.tar.gz
  sha256: 49f234fb3b31caabc1425e62d7ff88c57bd72e51eec1f6170a905d296c292363

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-matrix
  run:
    - r-base
    - r-matrix

test:
  commands:
    - $R -e "library('sparsesvd')"           # [not win]
    - "\"%R%\" -e \"library('sparsesvd')\""  # [win]

about:
  home: http://wordspace.r-forge.r-project.org/
  dev_url: https://github.com/lucasmaystre/svdlibc
  license: BSD-3-Clause
  summary: Wrapper around the 'SVDLIBC' library for (truncated) singular value decomposition of a sparse matrix. Currently, only sparse real matrices in Matrix package format are supported.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
