appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: cFrrnjDM3xH6FOwPmgAeR9bLtBQ08pjMk39nSApEMzh6ALZ9Va5YpLgSj3UeVoEOjA37+hPcLBBL47C7e7e7beN15Y5ykWZPR/v7GhUidHv6d5sS+YG4z6RzIiPrbLO0Ir/ewKDBp43kS3KJSkM5q9tfw4GEY8U3BUou1eUiZdxiScKjhAngOtdGnyrkNRFfZO2TqZTUaV1ShX6ikqqbt7cr7FO1XhL80FGUrEgE/fPvcsyEnnzLSyLhb3e/NAVmb0OYikbwYadH2hlwr4YgptZed06GvVv3cb9t6Sd8qkR3pGaFhdma0xsGqTPL9aSVI+SYu1SW+oCc9+EoSUYhTJSXrFA+3Xr+ubMh/8sbt7M/9EsFCxANmAE3xPai5s/D+1gyk4vsJQvtMRkxZz2nl7TKlptb/e0SbmnMEJT642zhizpTAeougjyRrKx2pJYRIvvd9ibImbH2mODrBAvWakWYXBh+a9VjUHe2H2zxcefUWXm6z0awyY0q4Q3K1va6q+6t/b6vFHcH5+gUH4xaUFKMdSpK+fD4VOPUefZQfXhuV8hLy5koi1tkmNpHQtItSMEb1tj50SGn9BEZMp1NxszdX5siv7bRSvtOBk7STliiHqeZH6HFCbimlE6qwBLA4caUEN+jou5fzBiQ/9cjUTnvh/rZW9Pnswj6ZZoMWeY=}
bot:
  automerge: true
